### ISSUE TITLE
Left a positive review for Gantry 5, someone deleted it, why?

### ISSUE THREAD

**Issue by MaghSamana** [joomla/jed-issues#68]
I recently begun to use Gantry 5 for my site, liked it, and thought to leave a positive review in Joomla! extensions. 
Someone deleted it, I wasn't notified about it, and there is no way I can leave a review there. Something seems to be very fishy here, if normal users can't post their reviews and opinions about the various extensions available. 

I expect an explanation. This wasn't normal.

**Comment by Llewellynvdm** [comment]
There issue is related to [Reviews disappearing](https://github.com/joomla/jed-issues/issues/8)

Can you give us more details, like the time and any other **public info** that could help @anibalsanchez trace the problem. Would you be willing to try submitting the review again? and then take screenshots of the before and after... so if it disappears you have some proof? It is hard to work with what we can't see.

**Comment by MaghSamana** [comment]
Hi,

I tried to resubmit the review but the system wouldn't let me.  All I get is:  
" Error
Not found! "

Time is recent, and for sure it was in December. Very likely in the last forthnight - though I don't remember exactly. The review was normal, and more or less said similar things with most other reviews there. I'm remaking an older website after quite some time ( it was in version 1.5), using latest Joomla!, and as work goes on, I write reviews for all extensions that are being tested or used on the site. Some of them are free, so it's a way of thanking the developers.

A couple of days ago, I went to leave another review and then I noticed that the number next to my username (which indicates reviews left) was less than it should be. I checked at my profile page and the previous review had simply disappeared. 

Is there a support email where I can send you my username, and check further what happened?

**Comment by anibalsanchez** [comment]
These GitHub issues are used to report system issues. We don't discuss here specific cases. 

If you submitted a review, and it flagged now, then it is removed and you can't submit a new review.

Please remember, the Joomla! Extensions Directory is not responsible for any extensions listed, nor does the JED Team provide support for extensions. All reviews submissions are subject to the [Terms of Service](https://extensions.joomla.org/about-jed/terms-of-service).

**Allowed and Encouraged**

- A full evaluation of the extension
- Courtesy and Honesty
- Pros & Cons of the extension and its performance
- Level of support received
- Ease of usage and deployment
- Purpose of using the extension (i.e., I used this extension for a magazine site.)
- Level of difficulty
- Your experience level with Joomla and web technologies

**Not allowed**

- Commercial disputes
- Questions to the Developer or Others
- Support/Feature Requests
- Error Messages
- Links
- Code or Bug Reports
- Questionable Language (including cursing)
- Submissions via an IP masking service or VPN
- One-line Reviews
- Self promotion or spam

As Llewellynvdm pointed out, it looks like your issue is the same than #8

**Comment by MaghSamana** [comment]
Hello,

The review would have been impossible to have been flagged, its content was just normal, and more or less similar to most other reviews posted there. Besides, I never received any notification, and only accidentally I noticed the review was missing.

Anyway, thanks for taking the time to answer, and I hope that these system problems are resolved.

**Comment by MaghSamana** [comment]
Another problem just showed up! 

Until a while ago, the reviews I had written with a positive rating (100) appeared normally. All of a sudden, they were changed into a rating of 80, and another field "value for money" appeared underneath, which wasn't there before. Now what is going on with this?

![untitled-1](https://user-images.githubusercontent.com/46110970/51111492-df7da500-1804-11e9-9a2b-35516f5d7900.jpg)

**Comment by anibalsanchez** [comment]
Which extension is showing -1 ?

**Comment by nikosdion** [comment]
That's Akeeba Backup. No, the user didn't contact me. I clicked on the link to this issue linked to #8 after receiving the GitHub notification of your reply, Anibal :) The screenshot caught my eye because I remember the wording; it absolutely made my day a few days ago! It is a review I received for Akeeba Backup on January 13th. 

Now, here's the fun part. The review shows on JED as 100%, see:
![image](https://user-images.githubusercontent.com/256041/51305991-f90d2f80-1a44-11e9-8e64-9bc0eed6f02c.png)
However, the user sees it as an 80% review with a field they never filled in... which is weird.

**Comment by anibalsanchez** [comment]
In the last month, we applied a new style to the site. **Value for Money** is a field that must not appear in free extensions. It is present at the database level (and the undefined value is -1), so it is possible that at some point the field was shown in the extension details.

Right now, it is working as expected, and  _Value for Money_ is not shown in Free extensions.

Since the original issue has been solved, if there no more updates, I'm closing the issue in 1-2 days.

**Comment by MaghSamana** [comment]
Well, nothing is solved yet. I logged in right now in joomla.org and in my profile panel I still see the reviews exactly as the appear in the screenshot, and the 'value for money' field is still there, despite the reviews being for free extensions.

And the issue about the review for Gantry 5 still remains. The one I wrote (it was also a 100% review) simply disappeared, there was no notification about it, and there is no explanation or ability to submit another.

**Comment by anibalsanchez** [comment]
Ok, I see you are referring to the reviews in the user profile.

We'll review the case of how reviews are being displayed in that area-

**Comment by MaghSamana** [comment]
It's been fixed! I just logged in now, and reviews in my user profile are displayed normally. 

So, it's only the missing Gantry 5 review now. I still can't post one, there.

**Comment by MaghSamana** [comment]
Hey, what on earth is going on now???????

I just left a review for Agosm free component/module (the developer helped a lot with support and helped solve a problem) and it again appears to have disappeared!!!! 

https://extensions.joomla.org/extensions/extension/maps-a-weather/maps-a-locations/agosm/

This can't be normal.......

**Comment by MaghSamana** [comment]
The number of reviews next to my profile name was changed from 6 to 5. The review I had posted just above the one shown in the screenshot disappeared - but the reviews number is still visible: 2 (mine was the second).


![untitled-1](https://user-images.githubusercontent.com/46110970/52053315-b4fc4d80-2561-11e9-9ad5-ad4a19ed6069.jpg)

**Comment by anibalsanchez** [comment]
Your reviews have been flagged. The system is detecting a **Submission via an IP masking service or VPN**.

Since the reviews are not disappearing or being deleted, I don't see an issue, and the system is working as expected.

**Comment by MaghSamana** [comment]
"Submission via an IP masking service or VPN."

It's from either a normal home connection from the largest telephony/internet provider of the country I reside, or from my workplace's network (a web development & digital design company). Nothing unusual.

[editing comment to add PS]
PS: After checking post times, here, the second review submission was from my home. And so was the first. Meaning it was from a standard home internet connection, without any IP masking or VPN. I never had VPN as a matter of fact. 

If possible, check the IP of all the recent reviews I have left, the ones that are still there and the removed ones - it's the same.

**Comment by MaghSamana** [comment]
Either way, your system is badly configured to attack normal organic reviews. And since the issue has been clarified, and it's been your error, I expect my reviews to be back and visible.

And when a system mistake is found out and recognised, the least you can do is reinstate those reviews. Why should I have to make another account simply to post these again? 

You have removed important information: the second review about Agosm, was about my attempts to get OpenStreetMaps working from within JCal Pro (there is only the google maps option built-in). The experiment was successful, especially with help from Agosm's developer who responded immediately and helped. He didn't have to and it's a free extension. I appreciated it a lot!!

Now, it is good for many people to read this and know that if they want to get rid of google maps, and wish to display OpenStreetMaps from within a component's environment (like JCal Pro), it is possible and I shared details about how it can be done. 

So I don't want to hear any excuses about what a badly configured system does, when you know that the flagged reviews were actually organic. Return the reviews online, and let valuable info be shared.

**Comment by anibalsanchez** [comment]
@MaghSamana There is no much we do about the validation

**Comment by anibalsanchez** [comment]
I mean in our internal discussions we know that we need to improve the "IP masking service or VPN" detection.

You could not be even aware of the usage of it in your networks. However, since the current controls reject your addresses, the reviews are not approved. 

By the way, this ticketing system is for reporting system issues, not for discussing personal cases.

**Comment by MaghSamana** [comment]
The thing is, that I posted all the recent reviews from the same home network/IP. Two of them got flagged, t the others didn't. From the same home network. So, it is a system problem.

And all these, frankly, make people fed up, while they come in good faith to review extensions that they use, and post information that will benefit other users. Especially free extensions are very important -  imagine how costly would have been to build a Joomla site, if everything was paid. The developers who provide something for free, be it frameworks or extensions, are doing a much-needed work, and one that keeps Joomla running and expanding. The least that can be done is to review their work and leave positives when we are using their extensions to built our sites or our clients' sites.

**Comment by anibalsanchez** [comment]
In your network, you could be sharing IPs with "bad neighbors". So, sometimes you work with different qualities of connections. 

In your case, we have double-checked your case, and the review raised several flags. So, it certainly not a system error.

**Comment by MaghSamana** [comment]
Let's make a test. I will create another account, and try to post the reviews again. And from the very same home/IP that I posted the others, where some of them are still there. I'll keep screenshots, see if there are any issues, and come back here to report the results of the experiment. 

So, let's sleep on it for now, and tomorrow I'll have more info on this.

**Comment by anibalsanchez** [comment]
To clarify the case of "pending processing" reviews, now reviews are only shown to the author until they are confirmed.

![star-review-2](https://user-images.githubusercontent.com/385780/52554966-b5f67000-2de8-11e9-92a9-40ae94acd173.png)

Issue solved. We are going to continue the efforts to improve the review system. Thanks for reporting.

**Comment by MaghSamana** [comment]
I have done the following tests. 

1. Posted another review from my account, same home network and IP - the one that was flagged in the two previously mentioned reviews. This one went through normally. 
2. Made a test account, and from the same home network and IP, posted two reviews, in the two extensions where the problem showed up. Again, both appeared normally.

So, there must have been a system glitch and false flagging in two extensions (Gantry 5 and Agosm), though it is unclear why. Without any changes to the home network/IP, I was able to post another regular review, and then to post the two missing ones from the second test account.
